apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealaf-sa
  namespace: sealaf-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealaf-role
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "issuers"
      - "certificates"
    verbs:
      - "create"
      - "delete"
      - "get"
  - apiGroups:
      - "apps.kubeblocks.io"
    resources:
      - "clusters"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - "objectstorage.sealos.io"
    resources:
      - "objectstorageusers"
      - "objectstoragebuckets"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebings
    verbs: ["get"]
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - "batch"
    resources:
      - "cronjobs"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "patch"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealaf-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealaf-role
subjects:
  - kind: ServiceAccount
    name: sealaf-sa
    namespace: sealaf-system